name: Tests

on:
  push:
    branches:
      - master
      - ticket/1
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.php != '7.2' && 'none' || 'xdebug }}

      - name: Run unit tests
        if: matrix.php == '7.2'
        run: |
          phpunit --coverage-clover=coverage.clover
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover

      - name: Run unit tests
        if: matrix.php != '7.2'
        run: |
          phpunit
